# Generated by Django 6.1.1 on 2026-09-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Дата и время окончания публикации", null=True
            ),
        ),
    ]
